name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
        - name: Deploy to QA
          uses: appleboy/ssh-action@v1.0.3
          with:
              host: ${{ secrets.QA_HOSTNAME }}
              username: ${{ secrets.QA_USERNAME }}
              key: ${{ secrets.PRIVATE_KEY }}
              port: 22
              script: |
                cd ~/first-discord-bot
                pm2 stop first-discord-bot
                git reset --hard origin/main 
                npm ci
                pm2 restart first-discord-bot
