name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: self-hosted
    if: ${{ github.event.pusher.name != 'github-actions[bot]' }}
    steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: false
        - run: npm version patch
        - run: git push
        - run: git push --tags