name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: self-hosted
    strategy:
      matrix:
          node-version: [20.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    permissions:
      contents: 'write'
      packages: 'write'
      actions: 'read'
    if: ${{ !endsWith(github.event.pusher.name, '[bot]') }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
        shell: bash
      - name: Bump version
        run: npm version patch
      - name: Push changes
        run: git push
      - name: Push tags
        run: git push --tags